services:
  # Spring Boot Web Service (using existing PostgreSQL database)
  - type: web
    name: coffee-shop-api
    runtime: java
    region: frankfurt  # Same region as your database for optimal performance
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod 