services:
  # Spring Boot Web Service (using existing PostgreSQL database)
  - type: web
    name: coffee-shop-api
    runtime: docker
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    dockerCommand: java -Dserver.port=$PORT -jar target/*.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod 